WebShopMatrixInc/Pages/Account.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using DataAccessLayer.Models;
using DataAccessLayer.Interfaces;
using DataAccessLayer.Repositories;
using Microsoft.AspNetCore.Mvc;

namespace WebShopMatrixInc.Pages;

public class AccountModel : PageModel
{
    private readonly ILogger<ProductViewModel> _logger;
    private readonly ICustomerRepository _customerRepository;
    public int? CustomerId { get; set; }
    public Customer? Customer { get; set; }

    public AccountModel(ILogger<ProductViewModel> logger, ICustomerRepository customerRepository)
    {
        _logger = logger;
        _customerRepository = customerRepository;
        CustomerId = -1;
    }
    
    public IActionResult OnGet()
    {
        CustomerId = HttpContext.Session.GetInt32("CustomerId") ?? -1;
        if (CustomerId == -1)
        {
            return Redirect("/Login");
        }
        else
        {
            Customer = _customerRepository.GetCustomerById(CustomerId.Value);
            return Page();
        }
    }
}

WebShopMatrixInc/Pages/Cart.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using DataAccessLayer.Interfaces;
using DataAccessLayer.Models;
using WebShopMatrixInc;

public class CartViewModel : PageModel
{
    private readonly ILogger<CartViewModel>? _logger;
    private readonly ICustomerRepository? _customerRepository;
    private readonly IOrderRepository? _orderRepository;
    
    public List<Product> Cart { get; private set; }
    public decimal TotalPrice { get; private set; }
    public int CustomerID { get; set; }
    public bool PlaceOrderFailed { get; set; }
    public bool OrderPlaced { get; set; }

    public CartViewModel(ILogger<CartViewModel> logger,
                        ICustomerRepository customerRepository, 
                        IOrderRepository orderRepository)
    {
        _logger = logger;
        _customerRepository = customerRepository;
        _orderRepository = orderRepository;
        Cart = new List<Product>();
        CustomerID = -1;
        PlaceOrderFailed = false;
        OrderPlaced = false;
    }

    public void OnGet()
    {
        Cart = HttpContext.Session.GetObjectFromJson<List<Product>>("Cart") ?? new List<Product>();
        TotalPrice = Cart.Sum(x => x.Price);
    }

    public IActionResult OnPost()
    {
        HttpContext.Session.Remove("Cart");
        Cart = new List<Product>();
        TotalPrice = 0;
        return RedirectToPage();
    }

    public IActionResult OnPostCreateOrder(int id)
    {
        CustomerID = HttpContext.Session.GetInt32("CustomerId") ?? -1;

        if (CustomerID == -1)
        {
            return RedirectToPage("/login");
        }
        
        var customer = _customerRepository.GetCustomerById(CustomerID);

        if (customer == null)
        {
            PlaceOrderFailed = true;
            return RedirectToPage("/login");
        }

        Cart = HttpContext.Session.GetObjectFromJson<List<Product>>("Cart") ?? new List<Product>();
        decimal orderTotal = Cart.Sum(x => x.Price);

        PlaceOrderFailed = false;
        
        _orderRepository.AddOrder(new Order
        {
            Customer = customer, 
            OrderDate = DateTime.Now, 
            Total = orderTotal
        });
        
        OrderPlaced = true;
        
        HttpContext.Session.Remove("Cart");
        Cart = new List<Product>();
        TotalPrice = 0;
        
        return RedirectToPage("/orderhistory");
    }
}

WebShopMatrixInc/Pages/CartView.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using DataAccessLayer.Interfaces;
using DataAccessLayer.Models;

namespace WebShopMatrixInc.Pages;

public class CartViewModel : PageModel
{
    private readonly ILogger<CartViewModel> _logger;
    private readonly IProductRepository? _productRepository;
    public List<Product> Cart { get; private set; }

    public Product Product { get; private set; }

    public CartViewModel(ILogger<CartViewModel> logger, IProductRepository productService)
    {
        _logger = logger;
        _productRepository = productService;
    }

    public void OnGet(int id)
    {
        Cart = HttpContext.Session.GetObjectFromJson<List<Product>>("Cart") ?? new List<Product>();
    }
}

WebShopMatrixInc/Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebShopMatrixInc.Pages;

[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
[IgnoreAntiforgeryToken]
public class ErrorModel : PageModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

    private readonly ILogger<ErrorModel> _logger;

    public ErrorModel(ILogger<ErrorModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
        RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
    }
}

WebShopMatrixInc/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using DataAccessLayer.Interfaces;
using DataAccessLayer.Models;

public class IndexModel : PageModel
{
    private readonly ILogger<IndexModel> _logger;
    private readonly IProductRepository? _productRepository;
    private readonly IPartRepository? _partRepository;
    [BindProperty]
    public string SelectedCategory { get; set; } = "All";

    public IEnumerable<Product> Products { get; set; } = new List<Product>();
    public IEnumerable<Part> Parts { get; set; } = new List<Part>();


    public IndexModel(ILogger<IndexModel> logger, IProductRepository productRepository, IPartRepository partRepository)
    {
        _logger = logger;
        _productRepository = productRepository;
        _partRepository = partRepository;
    }

    public void OnGet()
    {
        Products = _productRepository.GetAllProducts();
        Parts = _partRepository.GetAllParts();
    }
    
    public IActionResult OnPost()
    {
        _logger.LogInformation("Category selected: " + SelectedCategory);
        
        if (SelectedCategory == "All")
        {
            Products = _productRepository.GetAllProducts();
            return Page();      
        }
        
        Products = _productRepository.GetAllProducts().Where(p => p.Category == SelectedCategory);
        return Page();
    }
}

WebShopMatrixInc/Pages/Login.cshtml.cs
using DataAccessLayer.Interfaces;
using DataAccessLayer.Models;
using DataAccessLayer.Repositories;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace WebShopMatrixInc.Pages;

public class LoginModel : PageModel
{
    private readonly ILogger<ProductViewModel> _logger;
    private readonly ICustomerRepository _customerRepository;
    
    [BindProperty]
    public int? CustomerId { get; set; }
    public Customer? Customer { get; set; }
    public bool InvalidId { get; set; }
    
    public LoginModel(ILogger<ProductViewModel> logger, ICustomerRepository customerRepository)
    {
        _logger = logger;
        _customerRepository = customerRepository;
        InvalidId = false;
    }

    public void OnGet()
    {
        
    }

    public IActionResult OnPost()
    {
        Customer = _customerRepository.GetCustomerById(CustomerId.Value);

        if (Customer == null)
        {
            InvalidId = true;
            return Page();
        }
        
        InvalidId = false;
        
        HttpContext.Session.SetInt32("CustomerId", Customer.Id);
        
        return RedirectToPage("/account");
    }
}

WebShopMatrixInc/Pages/OrderHistory.cshtml.cs
using DataAccessLayer.Interfaces;
using DataAccessLayer.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebShopMatrixInc.Pages;

public class OrderHistoryModel : PageModel
{
    private ILogger<OrderHistoryModel> _logger;
    private IOrderRepository _orderRepository;
    private ICustomerRepository _customerRepository;

    public int CustomerId { get; set; }
    public IEnumerable<Order> CustomerOrders { get; set; }

    public OrderHistoryModel(ILogger<OrderHistoryModel> logger, IOrderRepository orderRepository, ICustomerRepository customerRepository)
    {
        _logger = logger;
        _orderRepository = orderRepository;
        _customerRepository = customerRepository;
    }

    public IActionResult OnGet()
    {
        CustomerId = HttpContext.Session.GetInt32("CustomerId") ?? -1;

        if (CustomerId == -1)
        {
            return Redirect("/Login");
        }
        else
        {
            CustomerOrders = _orderRepository.GetAllOrders().Where(o => o.CustomerId == CustomerId).ToList();
            return Page();
        }
    }
}

WebShopMatrixInc/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebShopMatrixInc.Pages;

public class PrivacyModel : PageModel
{
    private readonly ILogger<PrivacyModel> _logger;

    public PrivacyModel(ILogger<PrivacyModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
    }
}

WebShopMatrixInc/Pages/Product.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using DataAccessLayer.Interfaces;
using DataAccessLayer.Models;

namespace WebShopMatrixInc.Pages;

public class ProductViewModel : PageModel
{
    private readonly ILogger<ProductViewModel> _logger;
    private readonly IProductRepository? _productRepository;
    
    [BindProperty]
    public int Amount { get; set; } = 1;

    public Product Product { get; private set; }
    [TempData]
    public bool OrderPlaced { get; set; }

    public ProductViewModel(ILogger<ProductViewModel> logger, IProductRepository productService)
    {
        _logger = logger;
        _productRepository = productService;
        OrderPlaced = false;
    }

    public void OnGet(int id)
    {
        Product = _productRepository.GetProductById(id);
    }

    public IActionResult OnPost(int id)
    {
        var product = _productRepository.GetProductById(id);
        var cart = HttpContext.Session.GetObjectFromJson<List<Product>>("Cart") ?? new List<Product>();

        for (int i = 0; i < Amount; i++)
        {
            cart.Add(product);
        }
        
        HttpContext.Session.SetObjectAsJson("Cart", cart);
        
        _logger.LogInformation($"Added {Amount} of {product.Name} to cart");

        OrderPlaced = true;

        return RedirectToPage(new { id = id });
    }
}

WebShopMatrixInc/Pages/ProductView.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using DataAccessLayer.Interfaces;
using DataAccessLayer.Models;

namespace WebShopMatrixInc.Pages;

public class ProductViewModel : PageModel
{
    private readonly ILogger<ProductViewModel> _logger;
    private readonly IProductRepository? _productRepository;
    
    [BindProperty]
    public int Amount { get; set; } = 1;

    public Product Product { get; private set; }

    public ProductViewModel(ILogger<ProductViewModel> logger, IProductRepository productService)
    {
        _logger = logger;
        _productRepository = productService;
    }

    public void OnGet(int id)
    {
        Product = _productRepository.GetProductById(id);
    }

    public IActionResult OnPost(int id)
    {
        var product = _productRepository.GetProductById(id);
        var cart = HttpContext.Session.GetObjectFromJson<List<Product>>("Cart") ?? new List<Product>();

        for (int i = 0; i < Amount; i++)
        {
            cart.Add(product);
        }
        
        HttpContext.Session.SetObjectAsJson("Cart", cart);
        
        _logger.LogInformation($"Added {Amount} of {product.Name} to cart");

        return RedirectToPage(new { id = id });
    }
}

WebShopMatrixInc/Pages/Account.cshtml
@page "/account"
@using DataAccessLayer.Models
@model AccountModel

@{
    ViewData["Title"] = "Account";
}

@if (Model.Customer != null)
{
    <h1>Hello, @Model.Customer.Name</h1>
    <p>Configure your account on this page.</p>
}

WebShopMatrixInc/Pages/Cart.cshtml
@page "/cart"
@model CartViewModel
@{
    ViewData["Title"] = "Cart View Page";
}

<div>
    @if (Model.Cart.Count != 0)
    {
        <h1 class="display-4">My Shopping Cart</h1>

        <table class="table">
            <thead>
            <tr>
                <th>Image</th>
                <th>Name</th>
                <th>Description</th>
                <th>Price</th>
            </tr>
            </thead>
            <tbody>
            @foreach (var product in Model.Cart)
            {
                <tr>
                    <td>
                        @if (product.Image != null && product.Image.Length > 0)
                        {
                            <img src="@product.GetImageBase64()"
                                 alt="@product.Name"
                                 style="max-width: 100px; max-height: 100px;"/>
                        }
                    </td>
                    <td>
                        <a asp-page="ProductView"
                           asp-route-id="@product.Id">
                            @product.Name
                        </a>
                    </td>
                    <td>@product.Description</td>
                    <td>@product.Price.ToString("C")</td>
                </tr>
            }
            </tbody>
        </table>
        <p1>Total price: @Model.TotalPrice</p1>
        
        <div class="mt-3">
            <form method="post" asp-page-handler="CreateOrder" class="d-inline-block me-2">
                <button type="submit" class="btn btn-success">Place Order</button>
            </form>
            
            <form method="post" class="d-inline-block">
                <button class="btn btn-primary">Clear Cart</button>
            </form>
        </div>
        
        if (Model.PlaceOrderFailed)
        {
            <p style="color: red;">Failed to place order.</p>
        }

        if (Model.OrderPlaced)
        {
            <p style="color: green;">Order placed successfully.</p>
            <a asp-route="/orderhistory">See orders here.</a>
        }
    }
    else
    {
        <h1>Your shopping cart is empty!</h1>
        <p>Add products to the shopping cart to view them here.</p>
    }
</div>

WebShopMatrixInc/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="container-fluid">
    <div class="row">
        <div class="col-md-3 sidebar">
            <div>
                <h3>Filters</h3>
                <form method="post">
                    <div class="dropdown">
                        <p>Category</p>
                        <button class="btn btn-primary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                            @Model.SelectedCategory
                        </button>
                        <ul class="dropdown-menu">
                            <li>
                                <button type="submit" name="SelectedCategory" value="All" class="dropdown-item">All</button>
                            </li>
                            <li>
                                <button type="submit" name="SelectedCategory" value="Widget" class="dropdown-item">Widgets</button>
                            </li>
                            <li>
                                <button type="submit" name="SelectedCategory" value="Gadget" class="dropdown-item">Gadgets</button>
                            </li>
                            <li>
                                <button type="submit" name="SelectedCategory" value="Doohickey" class="dropdown-item">Doohickeys</button>
                            </li>

                        </ul>
                    </div>
                </form>

            </div>
        </div>
        <div class="col-md-9">
            <h1 class="display-4">Products</h1>
    
            <table class="table">
                <thead>
                <tr>
                    <th>Image</th>
                    <th>Name</th>
                    <th>Description</th>
                    <th>Price</th>
                </tr>
                </thead>
                <tbody>
                @foreach (var product in Model.Products)
                {
                    <tr>
                        <td>
                            @if (product.Image != null && product.Image.Length > 0)
                            {
                                <img src="@product.GetImageBase64()"
                                     alt="@product.Name" 
                                     style="max-width: 100px; max-height: 100px;" />
                            }
                        </td>
                        <td>
                            <a asp-page="Product"
                               asp-route-id="@product.Id">
                                @product.Name
                            </a>
                        </td>
                        <td>@product.Description</td>
                        <td>@product.Price.ToString("C")</td>
                    </tr>
                }
                </tbody>
            </table>
        </div>
    </div>
</div>

WebShopMatrixInc/Pages/Login.cshtml
@page "/login"
@model LoginModel

@{
    ViewData["Title"] = "Login";
}

<h1>Login</h1>
<form method="post">
    <label for="CustomerId">Account ID:</label>
    <input type="number" name="CustomerId" id="CustomerId" required />
    <button type="submit" class="btn btn-primary">Login</button>
</form>

@if (Model.InvalidId)
{
    <p>No account found for ID: @Model.CustomerId</p>
}

WebShopMatrixInc/Pages/OrderHistory.cshtml
@page "/OrderHistory"
@using DataAccessLayer.Models
@model OrderHistoryModel

@{
    ViewData["Title"] = "Order History";
}

@if (Model.CustomerOrders != null)
{
    <h2>Order History</h2>
    <table class="table">
        <thead>
        <tr>
            <th>Order ID</th>
            <th>Order Date</th>
            <th>Total Price</th>
        </tr>
        </thead>
        <tbody>
        @foreach (var order in Model.CustomerOrders)
        {
            <tr>
                <td>@order.Id</td>
                <td>@order.OrderDate.ToString()</td>
                <td>@order.Total.ToString("C")</td>
            </tr>
        }
        </tbody>
    </table>
}
else
{
    <p>No orders found for the current customer.</p>
}

WebShopMatrixInc/Pages/Product.cshtml
@page "/product/{id:int}"
@model ProductViewModel
@{
    ViewData["Title"] = Model.Product?.Name ?? "Product";
}

@if (Model.Product == null)
{
    <h2>Product not found</h2>
}
else
{
    <div class="product-container">
        <div class="product-image">
            <img src="@Model.Product.GetImageBase64()" alt="@Model.Product.Name" style="max-width: 300px;"/>
        </div>
        <div>
            <h1>@Model.Product.Name</h1>
            <p>Description: @Model.Product.Description</p>
            <p>Category: @Model.Product.Category</p>
            <p>Price: @Model.Product.Price.ToString("C")</p>

            <form method="post">
                <label for="quantity">Amount:</label>
                <input type="number" name="Amount" id="amount" min="1" value=@Model.Amount/>

                <input type="hidden" asp-for="Product.Id"/>
                <button type="submit" class="btn btn-primary">Add to Cart</button>
            </form>
            
            @if (Model.OrderPlaced)
            {
                <p style="color: green">
                    Added to shopping cart!
                    <a asp-page="/Cart">Go to shopping cart</a>
                </p>
            }
        </div>
    </div>
}

WebShopMatrixInc/Pages/ProductView.cshtml
@page "/product/{id:int}"
@model ProductViewModel
@{
    ViewData["Title"] = Model.Product?.Name ?? "Product";
}

@if (Model.Product == null)
{
    <h2>Product not found</h2>
}
else
{
    <div class="product-details">
        <h1>@Model.Product.Name</h1>
        <img src="@Model.Product.GetImageBase64()" alt="@Model.Product.Name" style="max-width: 300px;" />
        <p>Description: @Model.Product.Description</p>
        <p>Price: @Model.Product.Price.ToString("C")</p>
        <p>Amount</p>
        
        <form method="post">
            <label for="quantity">Amount:</label>
            <input type="number" name="Amount" id="amount" min="1" value=@Model.Amount />
            
            <input type="hidden" asp-for="Product.Id" />
            <button type="submit">Add to Cart</button>
        </form>
    </div>
}